	
			<footer>
				<div class="row">
					
					<div class="hours col-sm-3 col-sm-push-6">
						<h3>&#187; Hours</h3>
						<p>Monday - Friday: 7am - 9pm</p>
						<p>Saturday: 8am - 9pm</p>
						<p>Sunday: 9am - 4pm</p>
					</div>

					<div class="testimonials col-sm-3 col-sm-push-6">
						<h3>&#187; Testimonials</h3>
						<blockquote></blockquote>
						<p></p>
					</div>
					

					<div class="col-sm-6 col-sm-pull-6">
						<h3>&#187; Our Story</h3>
						<p>Caffe Nelle Cucine started as a small idea that grew into a full blown business. Pronounced: Cafe NEL-lay koo-Chee-nay,  the name,  literally means in Italian "Coffee In The Kitchens". In Italy, the traditional Cafe is a meeting place, a place where locals meetup, relax, gossip, or just take some time for themselves. We modeled Caffe Nelle Cucine after that experience.</p>
						<div id="about_toggle" class="collapse">
							<p>In a world that seems to be in hyperdrive, Caffe Nelle Cucine provides a comfortable space to take a breath and relax. Understanding that there's more to a coffeehouse than just an excellent cup of coffee or a well made cappuccino, we work to provide a comfortable and relaxing space for our customers to come and unwind after a long day.</p>
							<p>As a family run business, we are dedicated to being connected to our local community and getting to know our customers. We look forward to serving you the best cup of coffee you have ever had.</p>
						</div>
						<button type="button" class="view-more" id="about_more" data-toggle="collapse" data-target="#about_toggle">View More &#187;</button>
					</div>
				</div>
				
				<div class="row">
					<div class="copy col-xs-12">
						<p>Copyright &copy; Caffe Nelle Cucine 2012. All Rights Reserved.</p>
					</div>
				</div>
			</footer>
		

		</div>

		<script src="js/vendor/jquery-1.9.1.min.js"></script>
		<script src="js/vendor/angular-1.0.7.min.js"></script>
		<script src="js/vendor/bootstrap-3.0.0.min.js"></script>
		<script src="js/main.js"></script>

		<!-- Google Analytics: change UA-XXXXX-X to be your site's ID. 
		<script>
			var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
			(function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
			g.src='//www.google-analytics.com/ga.js';
			s.parentNode.insertBefore(g,s)}(document,'script'));
		</script>-->
	</body>
</html>