
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" ng-app="Caffe"> <!--<![endif]-->
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<title>{{ page_title }} | Caffe Nelle Cucine</title>
	<meta name="description" content="">
	<meta name="viewport" content="width=device-width">

	<link rel="stylesheet" href="css/bootstrap.css">
	<link rel="stylesheet" href="css/font-awesome.css">
	<link rel="stylesheet" href="css/main.css">
	<script src="js/vendor/modernizr-2.6.2.min.js"></script>
</head>
<body>
	<!--[if lt IE 7]>
		<p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
	<![endif]-->

	<div class="container">

		<header class="masthead clearfix">
			<a href="/" class="logo">Caffe Nelle Cucine</a>
			
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<i class="icon-reorder"></i>
			</button>
			
			<ul class="nav nav-justified navbar-collapse collapse">
				<li><a ng-href="/">Home</a></li>
				<li><a ng-href="#/coffeebar">Coffee Bar</a></li>
				<li><a ng-href="#/breakfast">Breakfast</a></li>
				<li><a ng-href="#/bakery">Baked Goods</a></li>
				<li><a ng-href="#/lunch">Lunch</a></li>
				<li><a ng-href="#/contact">Contact</a></li>
			</ul>

		</header>
